const province = [
  {
    label: "Nanggroe Aceh Darussalam (Ibu Kota Banda Aceh)",
    value: "Nanggroe Aceh Darussalam",
    ongkir: 60000,
  },
  { label: "Sumatera Utara (Ibu Kota Medan)", value: "Sumatera Utara", ongkir: 28000 },
  { label: "Sumatera Selatan (Ibu Kota Palembang)", value: "Sumatera Selatan", ongkir: 23000 },
  { label: "Sumatera Barat (Ibu Kota Padang)", value: "Sumatera Barat", ongkir: 26000 },
  { label: "Bengkulu (Ibu Kota Bengkulu)", value: "Bengkulu", ongkir: 23000 },
  { label: "Riau (Ibu Kota Pekanbaru)", value: "Riau", ongkir: 27000 },
  { label: "Kepulauan Riau (Ibu Kota Tanjung Pinang)", value: "Kepulauan Riau", ongkir: 38000 },
  { label: "Jambi (Ibu Kota Jambi)", value: "Jambi", ongkir: 24000 },
  { label: "Lampung (Ibu Kota Bandar Lampung)", value: "Lampung", ongkir: 21000 },
  { label: "Bangka Belitung (Ibu Kota Pangkal Pinang)", value: "Bangka Belitung", ongkir: 6000 },
  { label: "Kalimantan Barat (Ibu Kota Pontianak)", value: "Kalimantan Barat", ongkir: 51000 },
  { label: "Kalimantan Timur (Ibu Kota Samarinda)", value: "Kalimantan Timur", ongkir: 24000 },
  { label: "Kalimantan Selatan (Ibu Kota Banjarbaru)", value: "Kalimantan Selatan", ongkir: 29000 },
  { label: "Kalimantan Tengah (Ibu Kota Palangkaraya)", value: "Kalimantan Tengah", ongkir: 6000 },
  { label: "Kalimantan Utara (Ibu Kota Tanjung Selor)", value: "Kalimantan Utara", ongkir: 31000 },
  { label: "Banten (Ibu Kota Serang)", value: "Banten", ongkir: 33000 },
  { label: "DKI Jakarta (Ibu Kota Jakarta)", value: "DKI Jakarta", ongkir: 17000 },
  { label: "Jawa Barat (Ibu Kota Bandung)", value: "Jawa Barat", ongkir: 19000 },
  { label: "Jawa Tengah (Ibu Kota Semarang)", value: "Jawa Tengah", ongkir: 19000 },
  { label: "Daerah Istimewa Yogyakarta (Ibu Kota Yogyakarta)", value: "Daerah Istimewa Yogyakarta", ongkir: 20000 },
  { label: "Jawa Timur (Ibu Kota Surabaya)", value: "Jawa Timur", ongkir: 22000 },
  { label: "Bali (Ibu Kota Denpasar)", value: "Bali", ongkir: 22000 },
  { label: "Nusa Tenggara Timur (Ibu Kota Kupang)", value: "Nusa Tenggara Timur", ongkir: 30000 },
  { label: "Nusa Tenggara Barat (Ibu Kota Mataram)", value: "Nusa Tenggara Barat", ongkir: 40000 },
  { label: "Gorontalo (Ibu Kota Gorontalo)", value: "Gorontalo", ongkir: 29000 },
  { label: "Sulawesi Barat (Ibu Kota Mamuju)", value: "Sulawesi Barat", ongkir: 55000 },
  { label: "Sulawesi Tengah (Ibu Kota Palu)", value: "Sulawesi Tengah", ongkir: 29000 },
  { label: "Sulawesi Utara (Ibu Kota Manado)", value: "Sulawesi Utara", ongkir: 28000 },
  { label: "Sulawesi Tenggara (Ibu Kota Kendari)", value: "Sulawesi Tenggara", ongkir: 27000 },
  { label: "Sulawesi Selatan (Ibu Kota Makassar)", value: "Sulawesi Selatan", ongkir: 40000 },
  { label: "Maluku Utara (Ibu Kota Sofifi)", value: "Maluku Utara", ongkir: 97000 },
  { label: "Maluku (Ibu Kota Ambon)", value: "Maluku", ongkir: 44000 },
  { label: "Papua Barat (Ibu Kota Manokwari)", value: "Papua Barat", ongkir: 120000 },
  { label: "Papua (Ibu Kota Jayapura)", value: "Papua", ongkir: 82000 },
  { label: "Papua Tengah (Ibu Kota Nabire)", value: "Papua Tengah", ongkir: 108000 },
  { label: "Papua Pegunungan (Ibu Kota Jayawijaya)", value: "Papua Pegunungan", ongkir: 108000 },
  { label: "Papua Selatan (Ibu Kota Merauke)", value: "Papua Selatan", ongkir: 85000 },
  { label: "Papua Barat Daya (Ibu Kota Sorong)", value: "Papua Barat Daya", ongkir: 130000 },
];

export { province };
