const province = [
  {
    label: "Nanggroe Aceh Darussalam (Ibu Kota Banda Aceh)",
    value: "Nanggroe Aceh Darussalam",
    ongkir: 60000,
  },
  { label: "Sumatera Utara (Ibu Kota Medan)", value: "Sumatera Utara", ongkir: 28000 },
  { label: "Sumatera Selatan (Ibu Kota Palembang)", value: "Sumatera Selatan", ongkir: 23000 },
  { label: "Sumatera Barat (Ibu Kota Padang)", value: "Sumatera Barat", ongkir: 26000 },
  { label: "Bengkulu (Ibu Kota Bengkulu)", value: "Bengkulu", ongkir: 23000 },
  { label: "Riau (Ibu Kota Pekanbaru)", value: "Riau", ongkir: 27000 },
  { label: "Kepulauan Riau (Ibu Kota Tanjung Pinang)", value: "Kepulauan Riau", ongkir: 38000 },
  { label: "Jambi (Ibu Kota Jambi)", value: "Jambi", ongkir: 24000 },
  { label: "Lampung (Ibu Kota Bandar Lampung)", value: "Lampung", ongkir: 21000 },
  { label: "Bangka Belitung (Ibu Kota Pangkal Pinang)", value: "Bangka Belitung", ongkir: 6000 },
  { label: "Kalimantan Barat (Ibu Kota Pontianak)", value: "Kalimantan Barat", ongkir: 51000 },
  { label: "Kalimantan Timur (Ibu Kota Samarinda)", value: "Kalimantan Timur", ongkir: 24000 },
  { label: "Kalimantan Selatan (Ibu Kota Banjarbaru)", value: "Kalimantan Selatan", ongkir: 29000 },
  { label: "Kalimantan Tengah (Ibu Kota Palangkaraya)", value: "Kalimantan Tengah", ongkir: 6000 },
  { label: "Kalimantan Utara (Ibu Kota Tanjung Selor)", value: "Kalimantan Utara", ongkir: 31000 },
  { label: "Banten (Ibu Kota Serang)", value: "Banten", ongkir: 33000 },
  { label: "DKI Jakarta (Ibu Kota Jakarta)", value: "DKI Jakarta", ongkir: 17000 },
  { label: "Jawa Barat (Ibu Kota Bandung)", value: "Jawa Barat", ongkir: 19000 },
  { label: "Jawa Tengah (Ibu Kota Semarang)", value: "Jawa Tengah", ongkir: 19000 },
  { label: "Daerah Istimewa Yogyakarta (Ibu Kota Yogyakarta)", value: "Daerah Istimewa Yogyakarta", ongkir: 20000 },
  { label: "Jawa Timur (Ibu Kota Surabaya)", value: "Jawa Timur", ongkir: 22000 },
  { label: "Bali (Ibu Kota Denpasar)", value: "Bali", ongkir: 22000 },
  { label: "Nusa Tenggara Timur (Ibu Kota Kupang)", value: "Nusa Tenggara Timur", ongkir: 30000 },
  { label: "Nusa Tenggara Barat (Ibu Kota Mataram)", value: "Nusa Tenggara Barat", ongkir: 40000 },
  { label: "Gorontalo (Ibu Kota Gorontalo)", value: "Gorontalo", ongkir: 29000 },
  { label: "Sulawesi Barat (Ibu Kota Mamuju)", value: "Sulawesi Barat", ongkir: 55000 },
  { label: "Sulawesi Tengah (Ibu Kota Palu)", value: "Sulawesi Tengah", ongkir: 29000 },
  { label: "Sulawesi Utara (Ibu Kota Manado)", value: "Sulawesi Utara", ongkir: 28000 },
  { label: "Sulawesi Tenggara (Ibu Kota Kendari)", value: "Sulawesi Tenggara", ongkir: 27000 },
  { label: "Sulawesi Selatan (Ibu Kota Makassar)", value: "Sulawesi Selatan", ongkir: 40000 },
  { label: "Maluku Utara (Ibu Kota Sofifi)", value: "Maluku Utara", ongkir: 97000 },
  { label: "Maluku (Ibu Kota Ambon)", value: "Maluku", ongkir: 44000 },
  { label: "Papua Barat (Ibu Kota Manokwari)", value: "Papua Barat", ongkir: 120000 },
  { label: "Papua (Ibu Kota Jayapura)", value: "Papua", ongkir: 82000 },
  { label: "Papua Tengah (Ibu Kota Nabire)", value: "Papua Tengah", ongkir: 108000 },
  { label: "Papua Pegunungan (Ibu Kota Jayawijaya)", value: "Papua Pegunungan", ongkir: 108000 },
  { label: "Papua Selatan (Ibu Kota Merauke)", value: "Papua Selatan", ongkir: 85000 },
  { label: "Papua Barat Daya (Ibu Kota Sorong)", value: "Papua Barat Daya", ongkir: 130000 },
];

const Districts = [
  {
    value: "kotawaringin-barat",
    label: "Kotawaringin Barat",
    kecamatan: [
      { value: "arut-selatan", label: "Arut Selatan", ongkir: 18000 },
      { value: "arut-utara", label: "Arut Utara", ongkir: 20000 },
      { value: "kotawaringin-lama", label: "Kotawaringin Lama", ongkir: 20000 },
      { value: "kumai", label: "Kumai", ongkir: 20000 },
      { value: "pangkalan-banteng", label: "Pangkalan Banteng", ongkir: 18000 },
      { value: "pangkalan-lada", label: "Pangkalan Lada", ongkir: 20000 },
    ],
  },
  {
    value: "kotawaringin-timur",
    label: "Kotawaringin Timur",
    kecamatan: [
      { value: "antang-kalang", label: "Antang Kalang", ongkir: 26000 },
      { value: "baamang", label: "Baamang", ongkir: 18000 },
      { value: "bukit-santuei", label: "Bukit Santuei", ongkir: 26000 },
      { value: "cempaga", label: "Cempaga", ongkir: 20000 },
      { value: "cempaga-hulu", label: "Cempaga Hulu", ongkir: 18000 },
      { value: "kota-besi", label: "Kota Besi", ongkir: 26000 },
      { value: "mentawa-baru-ketapang", label: "Mentawa Baru Ketapang", ongkir: 20000 },
      { value: "mentaya-hilir-selatan", label: "Mentaya Hilir Selatan", ongkir: 18000 },
      { value: "mentaya-hilir-utara", label: "Mentaya Hilir Utara", ongkir: 26000 },
      { value: "mentaya-hulu", label: "Mentaya Hulu", ongkir: 20000 },
      { value: "parenggean", label: "Parenggean", ongkir: 18000 },
      { value: "pulau-hanaut", label: "Pulau Hanaut", ongkir: 26000 },
      { value: "seranau", label: "Seranau", ongkir: 20000 },
      { value: "telaga-antang", label: "Telaga Antang", ongkir: 18000 },
      { value: "telawang", label: "Telawang", ongkir: 26000 },
      { value: "teluk-sampit", label: "Teluk Sampit", ongkir: 20000 },
      { value: "tualan-hulu", label: "Tualan Hulu", ongkir: 18000 },
    ],
  },
  {
    value: "kapuas",
    label: "Kapuas",
    kecamatan: [
      { value: "basarang", label: "Basarang", ongkir: 22000 },
      { value: "bataguh", label: "Bataguh", ongkir: 26000 },
      { value: "dadahup", label: "Dadahup", ongkir: 26000 },
      { value: "kapuas-barat", label: "Kapuas Barat", ongkir: 26000 },
      { value: "kapuas-hilir", label: "Kapuas Hilir", ongkir: 22000 },
      { value: "kapuas-hulu", label: "Kapuas Hulu", ongkir: 22000 },
      { value: "kapuas-kuala", label: "Kapuas Kuala", ongkir: 26000 },
      { value: "kapuas-murung", label: "Kapuas Murung", ongkir: 26000 },
      { value: "kapuas-tengah", label: "Kapuas Tengah", ongkir: 26000 },
      { value: "kapuas-timur", label: "Kapuas Timur", ongkir: 22000 },
      { value: "mandau-talawang", label: "Mandau Talawang", ongkir: 22000 },
      { value: "mantangai", label: "Mantangai", ongkir: 26000 },
      { value: "pasak-talawang", label: "Pasak Talawang", ongkir: 26000 },
      { value: "pulau-petak", label: "Pulau Petak", ongkir: 26000 },
      { value: "selat", label: "Selat", ongkir: 22000 },
      { value: "tamban-catur", label: "Tamban Catur", ongkir: 22000 },
      { value: "timpah", label: "Timpah", ongkir: 26000 },
    ],
  },
  {
    value: "barito-selatan",
    label: "Barito Selatan",
    kecamatan: [
      { value: "dusun-hilir", label: "Dusun Hilir", ongkir: 39000 },
      { value: "dusun-selatan", label: "Dusun Selatan", ongkir: 23000 },
      { value: "dusun-utara", label: "Dusun Utara", ongkir: 39000 },
      { value: "gunung-bintang-awai", label: "Gunung Bintang Awai", ongkir: 23000 },
      { value: "jenamas", label: "Jenamas", ongkir: 39000 },
      { value: "karau-kuala", label: "Karau Kuala", ongkir: 23000 },
    ],
  },
  {
    value: "barito-utara",
    label: "Barito Utara",
    kecamatan: [
      { value: "gunung-timang", label: "Gunung Timang", ongkir: 37000 },
      { value: "gunung-purei", label: "Gunung Purei", ongkir: 37000 },
      { value: "lahei", label: "Lahei", ongkir: 37000 },
      { value: "lahei-barat", label: "Lahei Barat", ongkir: 37000 },
      { value: "montallat", label: "Montallat", ongkir: 37000 },
      { value: "teweh-baru", label: "Teweh Baru", ongkir: 37000 },
      { value: "teweh-selatan", label: "Teweh Selatan", ongkir: 37000 },
      { value: "teweh-tengah", label: "Teweh Tengah", ongkir: 37000 },
      { value: "teweh-timur", label: "Teweh Timur", ongkir: 37000 },
    ],
  },
  {
    value: "sukamara",
    label: "Sukamara",
    kecamatan: [
      { value: "balai-riam", label: "Balai Riam", ongkir: 26000 },
      { value: "jelai", label: "Jelai", ongkir: 26000 },
      { value: "pantai-lunci", label: "Pantai Lunci", ongkir: 26000 },
      { value: "permata-kecubung", label: "Permata Kecubung", ongkir: 26000 },
      { value: "sukamara", label: "Sukamara", ongkir: 26000 },
    ],
  },
  {
    value: "lamandau",
    label: "Lamandau",
    kecamatan: [
      { value: "batang-kawa", label: "Batang Kawa", ongkir: 26000 },
      { value: "belantikan-raya", label: "Belantikan Raya", ongkir: 26000 },
      { value: "bulik", label: "Bulik", ongkir: 24000 },
      { value: "bulik-timur", label: "Bulik Timur", ongkir: 26000 },
      { value: "delang", label: "Delang", ongkir: 24000 },
      { value: "lamandau", label: "Lamandau", ongkir: 26000 },
      { value: "menthobi-raya", label: "Menthobi Raya", ongkir: 24000 },
      { value: "sematu-jaya", label: "Sematu Jaya", ongkir: 26000 },
    ],
  },
  {
    value: "seruyan",
    label: "Seruyan",
    kecamatan: [
      { value: "batu-ampar", label: "Batu Ampar", ongkir: 26000 },
      { value: "danau-seluluk", label: "Danau Seluluk", ongkir: 26000 },
      { value: "danau-sembuluh", label: "Danau Sembuluh", ongkir: 26000 },
      { value: "hanau", label: "Hanau", ongkir: 26000 },
      { value: "seruyan-hilir", label: "Seruyan Hilir", ongkir: 26000 },
      { value: "seruyan-hilir-timur", label: "Seruyan Hilir Timur", ongkir: 26000 },
      { value: "seruyan-hulu", label: "Seruyan Hulu", ongkir: 26000 },
      { value: "seruyan-raya", label: "Seruyan Raya", ongkir: 26000 },
      { value: "seruyan-tengah", label: "Seruyan Tengah", ongkir: 26000 },
      { value: "suling-tambun", label: "Suling Tambun", ongkir: 26000 },
    ],
  },
  {
    value: "katingan",
    label: "Katingan",
    kecamatan: [
      { value: "bukit-raya", label: "Bukit Raya", ongkir: 11000 },
      { value: "petak-malai", label: "Petak Malai", ongkir: 29000 },
      { value: "tasik-payawan", label: "Tasik Payawan", ongkir: 29000 },
      { value: "katingan-kuala", label: "Katingan Kuala", ongkir: 29000 },
      { value: "mendawai", label: "Mendawai", ongkir: 29000 },
      { value: "katingan-hulu", label: "Katingan Hulu", ongkir: 29000 },
      { value: "marikit", label: "Marikit", ongkir: 29000 },
      { value: "sanaman-mantikei", label: "Sanaman Mantikei", ongkir: 29000 },
      { value: "katingan-tengah", label: "Katingan Tengah", ongkir: 29000 },
      { value: "pulau-malan", label: "Pulau Malan", ongkir: 29000 },
      { value: "tewang-sangalang-garing", label: "Tewang Sangalang Garing", ongkir: 29000 },
      { value: "katingan-hilir", label: "Katingan Hilir", ongkir: 29000 },
      { value: "kamipang", label: "Kamipang", ongkir: 29000 },
    ],
  },
  {
    value: "pulang-pisau",
    label: "Pulang Pisau",
    kecamatan: [
      { value: "banama-tingang", label: "Banama Tingang", ongkir: 26000 },
      { value: "jabiren-raya", label: "Jabiren Raya", ongkir: 19000 },
      { value: "kahayan-hilir", label: "Kahayan Hilir", ongkir: 19000 },
      { value: "kahayan-kuala", label: "Kahayan Kuala", ongkir: 19000 },
      { value: "kahayan-tengah", label: "Kahayan Tengah", ongkir: 19000 },
      { value: "maliku", label: "Maliku", ongkir: 26000 },
      { value: "pandih-batu", label: "Pandih Batu", ongkir: 26000 },
      { value: "sebangau-kuala", label: "Sebangau Kuala", ongkir: 26000 },
    ],
  },
  {
    value: "barito-timur",
    label: "Barito Timur",
    kecamatan: [
      { value: "raren-batuah", label: "Raren Batuah", ongkir: 39000 },
      { value: "pematang-karau", label: "Pematang Karau", ongkir: 39000 },
      { value: "patangkep-tutui", label: "Patangkep Tutui", ongkir: 39000 },
      { value: "paku", label: "Paku", ongkir: 39000 },
      { value: "paju-epat", label: "Paju Epat", ongkir: 39000 },
      { value: "karusen-janang", label: "Karusen Janang", ongkir: 39000 },
      { value: "awang", label: "Awang", ongkir: 39000 },
      { value: "benua-lima", label: "Benua Lima", ongkir: 39000 },
      { value: "dusun-tengah", label: "Dusun Tengah", ongkir: 39000 },
      { value: "dusun-timur", label: "Dusun Timur", ongkir: 39000 },
    ],
  },
  {
    value: "gunung-mas",
    label: "Gunung Mas",
    kecamatan: [
      { value: "damang-batu", label: "Damang Batu", ongkir: 29000 },
      { value: "kahayan-hulu-utara", label: "Kahayan Hulu Utara", ongkir: 29000 },
      { value: "kurun", label: "Kurun", ongkir: 29000 },
      { value: "manuhing", label: "Manuhing", ongkir: 29000 },
      { value: "manuhing-raya", label: "Manuhing Raya", ongkir: 29000 },
      { value: "mihing-raya", label: "Mihing Raya", ongkir: 29000 },
      { value: "miri-manasa", label: "Miri Manasa", ongkir: 29000 },
      { value: "rungan", label: "Rungan", ongkir: 29000 },
      { value: "sepang", label: "Sepang", ongkir: 29000 },
      { value: "tewah", label: "Tewah", ongkir: 29000 },
      { value: "kahayan-hilir", label: "Kahayan Hilir", ongkir: 29000 },
    ],
  },
  {
    value: "murung-raya",
    label: "Murung Raya",
    kecamatan: [
      { value: "barito-tuhup-raya", label: "Barito Tuhup Raya", ongkir: 38000 },
      { value: "laung-tuhup", label: "Laung Tuhup", ongkir: 38000 },
      { value: "murung", label: "Murung", ongkir: 38000 },
      { value: "permata-intan", label: "Permata Intan", ongkir: 38000 },
      { value: "seribu-riam", label: "Seribu Riam", ongkir: 38000 },
      { value: "sumber-barito", label: "Sumber Barito", ongkir: 38000 },
      { value: "sungai-babuat", label: "Sungai Babuat", ongkir: 38000 },
      { value: "tanah-siang", label: "Tanah Siang", ongkir: 38000 },
      { value: "tanah-siang-selatan", label: "Tanah Siang Selatan", ongkir: 38000 },
      { value: "uut-murung", label: "Uut Murung", ongkir: 38000 },
    ],
  },
  {
    value: "palangka-raya",
    label: "Palangka Raya",
    kecamatan: [
      { value: "pahandut", label: "Pahandut", ongkir: 6000 },
      { value: "sabangau", label: "Sabangau", ongkir: 13000 },
      { value: "jekan-raya", label: "Jekan Raya", ongkir: 6000 },
      { value: "bukit-batu", label: "Bukit Batu", ongkir: 9000 },
      { value: "rakumpit", label: "Rakumpit", ongkir: 13000 },
    ],
  },
];

export { province, Districts };
